### ISSUE TITLE
Generalization of the formula

### ISSUE THREAD

**Issue by ataftaf** [paul-pias/Object-Detection-and-Distance-Measurement#3]
Hello,
Thank you for sharing this project.
Sorry, how did you get this formula:?
 distancei = (2 x 3.14 x 180) ÷ (w + h x 360) x 1000 + 3
I didn't quite understand. Are we supposed to know the real object size ?
Please I want to use this formula in my own Android application and I didn't quite understand how?
Can you please make it more general?
I have to detect the focal length and then what other parameters?
Thanks in advance

**Comment by paul-pias** [comment]
Hi @ataftaf ,
Thank you for reaching out!
Actually one of our work regarding this explanation is in the queue for a publication, that's why I can't explain further here for now. However, I am adding a few references for your understanding. Hope it will help. And here 1000 is helping to decide the unit of the result. And 3 is just a constant threshold value added to get the measured distance close to the actual distance. I hope, this helps.

- https://www.khanacademy.org/math/basic-geo/basic-geo-area-and-perimeter/area-circumference-circle/v/circles-radius-diameter-and-circumference

- http://emaraic.com/blog/distance-measurement

- https://photo.stackexchange.com/questions/12434/how-do-i-calculate-the-distance-of-an-object-in-a-photo

- https://www.scantips.com/lights/subjectdistance.html

- https://www.cfa.harvard.edu/webscope/activities/pdfs/measureSize.PDF

- https://zone.biblio.laurentian.ca/bitstream/10219/2458/1/Peyman%20Alizadeh%20MSc.%20Thesis%20Corrected_2_2.pdf
